site_name: Dynamo DB CRI Python
site_description: Dynamo DB CRI Python
site_author: Agustin Navcevich

repo_url: https://github.com/agusnavce/dynamodb-cri-python
edit_uri: https://github.com/agusnavce/dynamodb-cri-python/edit/master/docs

theme: readthedocs

markdown_extensions:
  - codehilite:
      linenums: true

nav:
- Home: index.md
- Advanced: advanced.md
- About:
  - Release Notes: about/changelog.md
  - Contributing: about/contributing.md
  - License: about/license.md
